Repository MauryaRitesh/Facial-Expression-Detection, pull requests merged in 2023-10, with the labels that each got.

#21 Update README.md
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#26 Added language Translation
  README.md
  translation/README.Hindi.md
  translation/README.Japanese.md
Labels: hacktoberfest, hacktoberfest-accepted, docs

#23 Added colab notebook
  Facial_Expression_Detection.ipynb
Labels: enhancement, hacktoberfest

#25 fixed errors in README.md
  README.md
Labels: docs

#28 update docs
  CODE_OF_CONDUCT.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, docs

#27 doc(README): remove typo
  README.md
Labels: hacktoberfest-accepted, docs
